services:
  # 1. Сервис Брокера сообщений (Redis)
  redis:
    image: redis:7-alpine
    container_name: quicksay_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 2. Сервис Базы Данных (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: quicksay_postgres
    restart: always
    environment:
      POSTGRES_DB: ai_voice_bot_db
      POSTGRES_USER: bot_admin
      POSTGRES_PASSWORD: SuperSecurePass123!  # <- ВСТАВЬ СЮДА СВОЙ ПАРОЛЬ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. Сервис Telegram-Бота (bot.py)
  bot:
    build: .
    container_name: quicksay_bot
    restart: always
    command: python3 bot.py
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - ./downloads:/app/downloads

  # 4. Сервис Фонового Воркера (Celery)
  worker:
    build: .
    container_name: quicksay_worker
    restart: always
    command: celery -A tasks.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg

volumes:
  postgres_data:
  redis_data:
